/**
 * Inworld TTS Voice Mappings by Language
 * 
 * This file is auto-generated by scripts/fetch-inworld-voices.ts
 * Last updated: 2026-01-19T08:50:21.270Z
 * 
 * Maps ISO 639-1 language codes to available Inworld voices, organized by gender.
 * Used for automatic voice selection when language changes during conversation.
 */

export type VoiceGender = 'male' | 'female';

export interface LanguageVoiceMap {
  male: string[];
  female: string[];
}

/**
 * Voice mappings by language code (ISO 639-1)
 * 
 * Each language has arrays of voice IDs organized by gender.
 * Voices are ordered by preference (first voice is default for that gender).
 */
export const INWORLD_VOICES_BY_LANGUAGE: Record<string, LanguageVoiceMap> = {
  'en': {
    male: ['Alex', 'Craig', 'Dennis', 'Edward', 'Hades', 'Mark', 'Ronald', 'Shaun', 'Theodore', 'Timothy', 'Dominus', 'Clive', 'Carter', 'Blake', 'Pixie'],
    female: ['Ashley', 'Deborah', 'Elizabeth', 'Julia', 'Olivia', 'Priya', 'Sarah', 'Wendy', 'Hana', 'Luna', 'Pixie'],
  },
  'es': {
    male: ['Diego', 'Miguel', 'Rafael'],
    female: ['Lupita'],
  },
  'fr': {
    male: ['Alain', 'Mathieu', 'Étienne'],
    female: ['Hélène'],
  },
  'de': {
    male: ['Josef'],
    female: ['Johanna'],
  },
  'it': {
    male: ['Gianni', 'Orietta'],
    female: ['Orietta'],
  },
  'pt': {
    male: ['Heitor', 'Maitê'],
    female: ['Maitê'],
  },
  'ko': {
    male: ['Hyunwoo', 'Seojun'],
    female: ['Minji', 'Yoona'],
  },
  'zh': {
    male: ['Yichen'],
    female: ['Xiaoyin', 'Xinyi', 'Jing'],
  },
  'ja': {
    male: ['Satoshi'],
    female: ['Asuka'],
  },
  'nl': {
    male: ['Erik', 'Lennart'],
    female: ['Katrien', 'Lore'],
  },
  'pl': {
    male: ['Szymon', 'Wojciech'],
    female: [],
  },
  'ru': {
    male: ['Dmitry', 'Nikolai'],
    female: ['Svetlana', 'Elena'],
  },
} as const;

/**
 * Get all supported language codes
 */
export function getSupportedLanguages(): string[] {
  return Object.keys(INWORLD_VOICES_BY_LANGUAGE);
}

/**
 * Get available voices for a language
 */
export function getVoicesForLanguage(language: string): LanguageVoiceMap | undefined {
  return INWORLD_VOICES_BY_LANGUAGE[language];
}

/**
 * Check if a language is supported
 */
export function isLanguageSupported(language: string): boolean {
  return language in INWORLD_VOICES_BY_LANGUAGE;
}
